
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwlpdoqtkfjbjectmwtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3bHBkb3F0a2ZqYmplY3Rtd3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjM4MTQsImV4cCI6MjA2Mjk5OTgxNH0.EBui8-hJ8MnEHQonO4YSIyTZI7su3NU_QAjF8tYd1Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Helper function to handle Supabase errors consistently
 * @param error The error object from Supabase
 * @param defaultMessage Default message to show if error cannot be parsed
 * @returns User-friendly error message
 */
export const handleSupabaseError = (error: any, defaultMessage = "An unexpected error occurred"): string => {
  if (!error) return defaultMessage;
  
  // Check if it's a Supabase error with message
  if (error.message) {
    // Handle specific Supabase error codes
    if (error.code) {
      switch (error.code) {
        case "PGRST116": 
          return "No data found";
        case "23505": 
          return "A record with this information already exists";
        case "23503": 
          return "This operation failed because it references non-existent data";
        case "42P01": 
          return "Database configuration error: Table not found";
        case "42601": 
          return "Invalid SQL syntax";
        default:
          return error.message;
      }
    }
    
    return error.message;
  }
  
  // Handle edge function errors
  if (typeof error === 'object' && error.error) {
    return error.error;
  }
  
  return defaultMessage;
};

/**
 * Retry a Supabase operation with exponential backoff
 * @param operation The async operation to retry
 * @param maxRetries Maximum number of retries
 * @param delay Initial delay in ms
 * @returns The result of the operation
 */
export const retryOperation = async <T>(
  operation: () => Promise<T>, 
  maxRetries = 3,
  delay = 500
): Promise<T> => {
  let lastError: any;
  
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await operation();
    } catch (error) {
      lastError = error;
      
      // Don't wait on the last attempt
      if (attempt < maxRetries) {
        // Exponential backoff with jitter
        const backoff = delay * Math.pow(2, attempt) * (0.9 + Math.random() * 0.2);
        await new Promise(resolve => setTimeout(resolve, backoff));
      }
    }
  }
  
  throw lastError;
};
