// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwlpdoqtkfjbjectmwtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3bHBkb3F0a2ZqYmplY3Rtd3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjM4MTQsImV4cCI6MjA2Mjk5OTgxNH0.EBui8-hJ8MnEHQonO4YSIyTZI7su3NU_QAjF8tYd1Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);